### PR TITLE
Threads example

### PR DESCRIPTION
**Pull request by Zdancewic**
An example using extraction and an OCaml "driver" for an itrees program that does round-robin scheduling of three threads.

### CODE REVIEW

**Comment by gmalecha** [comment]
This is cool. If I understand correctly, the limitation here is that you can't spawn threads that spawn threads. Is that right?

**Comment by Zdancewic** [comment]
@gmalecha Well, you can spawn threads that spawn threads, but those "internal" threads have to be handled by a different scheduler.  I don't know if it's possible to set things up so that the spawned threads can be handled by the same scheduler.

**Comment by Lysxia** [comment]
(Rebased to integrate the recent paco updates.)

> I don't know if it's possible to set things up so that the spawned threads can be handled by the same scheduler.

The last commit I just added lifts that limitation.

**Comment by Zdancewic** [comment]
Nice!  Shall we merge this to master too?

**Pull request merged**
