### PR TITLE
simplify the definition of bind to avoid unnecessary taus

### PR DESCRIPTION
**Pull request by gmalecha**
This simplifies the definition of `bind` based on the discussion in #9 . I haven't had a chance to update the proofs in `Equivalence.v` yet. Are you guys building on top of those proofs?

### CODE REVIEW

**Comment by Lysxia** [comment]
We aren't yet.

**Comment by gmalecha** [comment]
Note that with this PR, the `Equivalence.v` file no longer compiles.

**Comment by gmalecha** [comment]
I also just realized that this means that `hoist` should no longer be necessary since `forall i f, hoist f i = hom (fun _ e => Vis e Ret) i` since `bind` doesn't introduce extra `Tau`s now.

I believe it is that case (though it would be difficult to state) that there are only two ways to get `Tau`s if you use regular combinators (i.e. `bind`, `ret`, `mfix`): 1. You write a program that is equivalent to `spin`; 2. you use `hom` to interpret an effect "fully", i.e. the meaning of an effect is a `ret`.

**Comment by gmalecha** [comment]
I did a bit more refactoring trying to split out some of the functionality (I'm a fan of small, self-contained files). In going through `Effects.v`, it seems like there are a lot of places where we re-implement `hom` (I renamed it to `interp`). Now that we don't need to worry about "economical" mappings (since `bind` doesn't introduce `Tau`s), we should be able to consolidate these. In general, for each new effect we have, we should be able to pick an appropriate monad to interpret it and then use the appropriate `eff_hom`. For example, if we pick the identity monad, we use `eff_hom`, if we use the state monad we pick `eff_hom_s`. There can be similar `eff_hom`s for other monads, one of the more exotic ones is `interp_prop` which interprets into the monad formed by `fun x => x -> Prop` (with the usual `bind` and `ret`).

**Pull request merged**
