### PR TITLE
Licence and OPAM

### PR DESCRIPTION
**Pull request by liyishuai**
Prepare for releasing on [coq-extra-dev](/coq/opam-coq-archive/tree/master/extra-dev).
## Added
- MIT license
- `opam` file

### CODE REVIEW

**Comment by Lysxia** [comment]
I'm fine with MIT license. What do @gmalecha and @Zdancewic think?

**Comment by gmalecha** [comment]
MIT works for me.

**Comment by gmalecha** [comment]
I think that #30 should be merged before this.

**Comment by Zdancewic** [comment]
I'm also fine with MIT license.  I think we can probably add this now.

**Comment by Lysxia** [comment]
Great! @liyishuai I'll let you release on extra-dev. @Zdancewic can you enable Travis? (I guess you need admin rights to do that.)

**Comment by liyishuai** [comment]
Proposed: coq/opam-coq-archive#527

**Pull request merged**
