### PR TITLE
Update with paco-2.1.0.

### PR DESCRIPTION
**Pull request by gilhur**

### CODE REVIEW

**Comment by gilhur** [comment]
The examples directory fails to build, but the same happens in the master branch. Please fix it in the master.

**Comment by YaZko** [comment]
Sorry about that, it should be fixed in master now.

**Comment by Zdancewic** [comment]
@YaZko -- thanks!  I also just added Factorial.v to the examples so that we make sure to keep it up to date with changes.

**Comment by gilhur** [comment]
Since coq-paco-2.1.0 is available, I think it is time to merge this PR.

**Pull request merged**
