### PR TITLE
opam: Compatible with 8.11

### PR DESCRIPTION
**Pull request by liyishuai**
- [x] coq/opam-coq-archive#1156
- [x] coq/opam-coq-archive#1159

### CODE REVIEW

**Comment by liyishuai** [comment]
Ready to merge.

**Comment by Lysxia** [comment]
@Zdancewic since you have the rights for it, could you

1. merge this if you agree to do the next step;

2. activate InteractionTrees on CircleCI (should be at this address https://circleci.com/gh/organizations/DeepSpec/settings#projects);

3. deactivate it on TravisCI (somewhere under https://travis-ci.com/account/repositories after clicking on DeepSpec)?

**Comment by Zdancewic** [comment]
@Lysxia OK -- I've activated the CircleCI.   There's a new ITrees branch for circle configuration:
https://github.com/DeepSpec/InteractionTrees/tree/circleci-project-setup

I'm working on deactivating Travis, but it seems to be a pain...

**Comment by Lysxia** [comment]
Hmm, branch master should already be set up for CircleCI with this PR.

**Comment by Zdancewic** [comment]
The default CircleCI framework creates the branch automatically when it's linked with a github project, so it's probably OK to delete it and use your configuration.  

By the way, I'm having trouble figuring out how to disable Travis -- there doesn't seem to be an "off switch" and googling hasn't turned up anything applicable.

**Comment by Lysxia** [comment]
On closer inspection, it seems that travis-ci.com has a different interface from travis-ci.org, and all repositories it has access to are always tracked. The repositories Travis has access to are controlled on Github's side (Settings > Applications). I don't know how different it is for organizations though.

**Pull request merged**
