### PR TITLE
Use coq-paco-2.0.3.

### PR DESCRIPTION
**Pull request by gilhur**
- do not merge until coq-paco-2.0.3 is available.

### CODE REVIEW

**Comment by Lysxia** [comment]
Can you also update the minimum version in the file `coq-itree.opam`?

**Comment by gilhur** [comment]
> Can you also update the minimum version in the file `coq-itree.opam`?

I just updated it and fixed conflicts with the master.

**Comment by Lysxia** [comment]
Is this ready to merge?

**Comment by gilhur** [comment]
> Is this ready to merge?

Yes, it is ready to merge.

**Comment by Lysxia** [comment]
Thanks Gil!

**Pull request merged**
