### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by Zdancewic**

### CODE REVIEW

**Comment by Zdancewic** [comment]
Just some slight notation and commenting changes.

**Comment by Zdancewic** [comment]
I plan to do a bit more polishing / cleanup in Eq.v and UpToTau.v next.

**Comment by YaZko** [comment]
Just in case to avoid duplicating some work, be wary that the compiler branch has led to a lot of changes in Eq and UptoTau: both eq_itree and eutt have been parameterized by a relation over the return type, rather than impose equality.

**Comment by Lysxia** [comment]
Some of the renaming here (esp. regarding the use of `_` or `F` suffixes) also overlaps with what took place on the imp2asm branch.

**Comment by Zdancewic** [comment]
Ah -- good to know.  I'll hold off doing more cleanup until we merge that branch, then.

**Comment by gmalecha** [comment]
What is the right thing to do with this PR? Merge it into the Imp2Asm branch?

**Comment by Lysxia** [comment]
I believe the changes have been merged into imp2asm.

**Pull request closed without merging**
